//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tareas
    {
        public int ID_Tarea { get; set; }
        public string Titulo_de_Tarea { get; set; }
        public string Observacion { get; set; }
        public string Tipo_de_Tarea { get; set; }
        public string Nivel_de_Prioridad { get; set; }
        public string Estado { get; set; }
        public string Tiempo_estimado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
